### ISSUE TITLE
La informacion de la sopa de letras se pierde

### ISSUE THREAD

**Issue by josecadima** [juanpablobadani/UCB_SopaDeLetras#2]
El problema es que cuando se ingresa la informacion desde teclado, la info se guarda en una estructura internamente dentro del metodo. Lo que falta es guardar lo que retorna el metodo en otra variable antes de enviarla al metodo mostrar.

informacion = IngresarInformacioJuego();

**Comment by juanpablobadani** [comment]
Como no me di cuenta ya lo solucione
